# Generated by Django 6.0.5 on 2026-05-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content',
            field=models.TextField(default='', verbose_name='Текст документа (Регламент, FAQ)'),
        ),
    ]
