# Generated by Django 6.0.5 on 2026-05-12 00:25

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_document_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True, verbose_name='Векторное представление'),
        ),
    ]
