# Generated by Django 6.0.5 on 2026-05-12 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_documentchunk_embedding'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='documentchunk',
            name='embedding_hnsw_idx',
        ),
    ]
